name: Feature Request
description: Schlagen Sie eine neue Funktion oder Verbesserung vor
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees:
  - Mauritz-Langer

body:
  - type: markdown
    attributes:
      value: |
        Vielen Dank für Ihren Verbesserungsvorschlag! Bitte beschreiben Sie Ihre Idee.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature-Beschreibung
      description: Beschreiben Sie die gewünschte Funktion
      placeholder: Was soll die neue Funktion können?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Warum wäre diese Funktion nützlich?
      placeholder: Welches Problem löst diese Funktion?
    validations:
      required: true
name: Bug Report
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativen
      description: Haben Sie alternative Lösungen in Betracht gezogen?
      placeholder: Gibt es andere Wege, das Problem zu lösen?

  - type: dropdown
    id: priority
    attributes:
      label: Priorität
      description: Wie wichtig ist diese Funktion für Sie?
      options:
        - Niedrig
        - Mittel
        - Hoch
        - Kritisch
    validations:
      required: true
description: Melden Sie einen Fehler oder ein Problem
title: "[BUG] "
labels: ["bug", "triage"]
assignees:
  - Mauritz-Langer

body:
  - type: markdown
    attributes:
      value: |
        Vielen Dank, dass Sie einen Bug-Report erstellen! Bitte füllen Sie die folgenden Felder aus.

  - type: input
    id: browser
    attributes:
      label: Browser und Version
      description: Welcher Browser und welche Version wird verwendet?
      placeholder: z.B. Chrome 119.0.6045.105
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Gerät
      description: Auf welchem Gerät tritt das Problem auf?
      options:
        - Desktop
        - Tablet
        - Smartphone
        - Andere
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Fehlerbeschreibung
      description: Beschreiben Sie den Fehler so detailliert wie möglich
      placeholder: Was ist passiert und was haben Sie erwartet?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Schritte zur Reproduktion
      description: Wie kann der Fehler reproduziert werden?
      placeholder: |
        1. Gehe zu...
        2. Klicke auf...
        3. Scrolle zu...
        4. Fehler tritt auf
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Zusätzliche Informationen
      description: Screenshots, Konsolen-Logs oder andere hilfreiche Informationen
      placeholder: Fügen Sie hier weitere Details hinzu
