name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '*'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate release
        run: |
          npx semantic-release
